import os

from dotenv import load_dotenv

load_dotenv()

# jwt
ACCESS_TOKEN_SECRET = os.getenv("ACCESS_TOKEN_SECRET")
REFRESH_TOKEN_SECRET = os.getenv("REFRESH_TOKEN_SECRET")
ACCESS_TOKEN_EXPIRED_TIME_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRED_TIME_MINUTES"))
REFRESH_TOKEN_EXPIRED_TIME_DAYS = int(os.getenv("REFRESH_TOKEN_EXPIRED_TIME_DAYS"))
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM")
TOKEN_ISSUER = os.getenv("TOKEN_ISSUER")
